-- Initial schema generated by lapigo. DO NOT EDIT.

CREATE TABLE "articles" (
    "id" uuid NOT NULL,
    "title" varchar(200) NOT NULL,
    "body" text,
    "status" text NOT NULL,
    "slug" text,
    "author_id" uuid,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "version" integer,
    CONSTRAINT articles_pkey PRIMARY KEY ("id"),
    CONSTRAINT articles_slug_key UNIQUE ("slug"),
    CONSTRAINT articles_status_check CHECK ("status" IN ('draft', 'published'))
);

CREATE TABLE "users" (
    "id" uuid NOT NULL,
    "email" text NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY ("id"),
    CONSTRAINT users_email_key UNIQUE ("email")
);

ALTER TABLE "articles" ADD CONSTRAINT articles_author_id_fkey FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE RESTRICT;

CREATE INDEX articles_status_created_at_id_idx ON "articles" ("status", "created_at", "id");
CREATE INDEX articles_author_id_created_at_id_idx ON "articles" ("author_id", "created_at", "id");
CREATE INDEX articles_created_at_id_idx ON "articles" ("created_at", "id");
