-- Initial schema generated by lapigo. DO NOT EDIT.

CREATE TABLE "gizmos" (
    "id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "state" text DEFAULT 'active',
    "quota" integer DEFAULT '5',
    CONSTRAINT gizmos_pkey PRIMARY KEY ("id")
);

CREATE INDEX gizmos_created_at_id_idx ON "gizmos" ("created_at", "id");
