-- Initial schema generated by lapigo. DO NOT EDIT.

CREATE TABLE "tags" (
    "id" uuid NOT NULL,
    "kind" text NOT NULL,
    CONSTRAINT tags_pkey PRIMARY KEY ("id"),
    CONSTRAINT tags_kind_check CHECK ("kind" IN ('it''s', 'plain'))
);
