-- Initial schema generated by lapigo. DO NOT EDIT.

CREATE TABLE "profiles" (
    "id" uuid NOT NULL,
    "user_id" uuid,
    CONSTRAINT profiles_pkey PRIMARY KEY ("id")
);

CREATE TABLE "users" (
    "id" uuid NOT NULL,
    "profile_id" uuid,
    CONSTRAINT users_pkey PRIMARY KEY ("id")
);

ALTER TABLE "profiles" ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "users" ADD CONSTRAINT users_profile_id_fkey FOREIGN KEY ("profile_id") REFERENCES "profiles" ("id") ON DELETE RESTRICT;
