-- Initial schema generated by lapigo. DO NOT EDIT.

CREATE TABLE "posts" (
    "id" uuid NOT NULL,
    "status" text NOT NULL,
    CONSTRAINT posts_pkey PRIMARY KEY ("id"),
    CONSTRAINT posts_status_check CHECK ("status" IN ('draft', 'published'))
);

CREATE INDEX posts_status_id_idx ON "posts" ("status", "id");
