-- Initial schema generated by lapigo. DO NOT EDIT.

CREATE TABLE "widgets" (
    "id" uuid NOT NULL,
    "a_b" text NOT NULL,
    "a" text NOT NULL,
    "b" text NOT NULL,
    CONSTRAINT widgets_pkey PRIMARY KEY ("id")
);

CREATE INDEX widgets_a_b_id_idx ON "widgets" ("a_b", "id");
CREATE INDEX widgets_a_id_idx ON "widgets" ("a", "id");
CREATE INDEX widgets_b_id_idx ON "widgets" ("b", "id");
CREATE INDEX widgets_a_b_id_idx_50971b9c8f0e699d ON "widgets" ("a", "b", "id");
