-- Initial schema generated by lapigo. DO NOT EDIT.

CREATE TABLE "table_with_a_deliberately_long_table_name" (
    "id" uuid NOT NULL,
    "created_at" timestamptz NOT NULL,
    "filter_column_with_a_deliberately_long_name" text NOT NULL,
    "a_unique_column_with_an_extremely_long_name_here_too" text,
    CONSTRAINT table_with_a_deliberately_long_table_name_pkey PRIMARY KEY ("id"),
    CONSTRAINT table_with_a_deliberately_long_table_name_a_uni_78b8ca33dc711b6 UNIQUE ("a_unique_column_with_an_extremely_long_name_here_too")
);

CREATE INDEX table_with_a_deliberately_long_table_name_filt_a1e6d1bad8255bff ON "table_with_a_deliberately_long_table_name" ("filter_column_with_a_deliberately_long_name", "created_at", "id");
CREATE INDEX table_with_a_deliberately_long_table_name_created_at_id_idx ON "table_with_a_deliberately_long_table_name" ("created_at", "id");
