-- Initial schema generated by lapigo. DO NOT EDIT.

CREATE TABLE "groupings" (
    "id" uuid NOT NULL,
    CONSTRAINT groupings_pkey PRIMARY KEY ("id")
);

CREATE TABLE "order" (
    "id" uuid NOT NULL,
    "select" text NOT NULL,
    "user_id" uuid,
    "where" text,
    CONSTRAINT order_pkey PRIMARY KEY ("id")
);

ALTER TABLE "order" ADD CONSTRAINT order_user_id_fkey FOREIGN KEY ("user_id") REFERENCES "groupings" ("id") ON DELETE CASCADE;

CREATE INDEX order_select_id_idx ON "order" ("select", "id");
