-- Initial schema generated by lapigo. DO NOT EDIT.

CREATE TABLE "employees" (
    "id" uuid NOT NULL,
    "manager_id" uuid,
    CONSTRAINT employees_pkey PRIMARY KEY ("id")
);

ALTER TABLE "employees" ADD CONSTRAINT employees_manager_id_fkey FOREIGN KEY ("manager_id") REFERENCES "employees" ("id") ON DELETE RESTRICT;
