// Package ddl renders a frozen, validated *ir.Schema into the initial
// migration SQL phase 1 owns (spec §1, §7.2): one CREATE TABLE per entity
// with its column types (spec §3.2) and constraints, foreign keys as ALTER
// TABLE statements, and the index set spec §7.2 derives from the declared
// sort and filters plus any declared composite indexes (spec §3.5).
//
// Emit is a pure function of the IR: no filesystem, no clock, no map ranging
// reaches the output, so the same schema always renders byte-identical SQL
// (spec §5.3). Step 5's writer routes these bytes into
// migrations/0001_init.sql, written once and never rewritten (spec §6.1);
// this package never touches a file.
//
// Emit assumes a schema that internal/parse produced and internal/validate
// accepted: identifiers match the parser's identifier grammar, sort keys are
// non-empty and legal, and declared index columns are declared filters. Those
// guarantees are what allow Emit to be total -- no error return -- and
// emitting unvalidated SQL literals is the failure mode the parser's enum
// value rules exist to close.
package ddl

import (
	"fmt"
	"hash/fnv"
	"strings"

	"github.com/cdhdt/lapigo/internal/ir"
)

// maxIdentifierBytes is Postgres's identifier length limit (NAMEDATALEN-1).
// A longer name is not rejected -- it is silently truncated, so two distinct
// indexes whose names share a 63-byte prefix would collide as far as Postgres
// is concerned. Names this package derives never rely on that: anything
// longer is truncated here, deterministically, with a hash of the full name
// appended so prefix-sharing names still differ.
const maxIdentifierBytes = 63

// Emit renders schema's initial migration SQL. A nil schema renders nothing
// (nil), the same courtesy validate.Validate extends the caller that
// forwards parse.Parse's two return values straight in.
func Emit(schema *ir.Schema) []byte {
	if schema == nil {
		return nil
	}
	em := &emitter{names: make(map[string]bool)}
	em.header()
	for _, e := range schema.Entities {
		em.table(e)
	}
	for _, e := range schema.Entities {
		em.foreignKeys(e)
	}
	for _, e := range schema.Entities {
		em.indexes(e)
	}
	// Every statement writer ends its output with "\n\n"; an entity whose
	// index group is empty (its only index was the primary key's own) would
	// otherwise leave the file ending in a stack of blank lines. One final
	// newline, always.
	out := strings.TrimRight(em.b.String(), "\n")
	return []byte(out + "\n")
}

// emitter carries the output buffer and the one piece of state that must
// outlive a single statement: every CREATE INDEX name emitted so far. Index
// names are database-scoped in Postgres (unlike constraint names, which are
// table-scoped), so uniqueness is decided across the whole file, not per
// table.
type emitter struct {
	b     strings.Builder
	names map[string]bool
}

func (em *emitter) header() {
	// No timestamp, no version: both make the output non-deterministic or
	// build-dependent (spec §5.3). The migration is written once, so a
	// "generated by" marker adds nothing the lock does not already record.
	em.b.WriteString("-- Initial schema generated by lapigo. DO NOT EDIT.\n\n")
}

// table emits one entity's CREATE TABLE: columns in declaration order, then
// the primary key, then UNIQUE constraints, then enum CHECK constraints, in
// declaration order within each group. Column types come from
// ir.Field.PgType (spec §3.2); a `max:` on a string already upgraded it to
// varchar(n) there.
func (em *emitter) table(e *ir.Entity) {
	em.b.WriteString("CREATE TABLE ")
	em.b.WriteString(quoteIdent(e.Table))
	em.b.WriteString(" (\n")
	for _, f := range e.Fields {
		em.b.WriteString("    ")
		em.b.WriteString(quoteIdent(f.Column))
		em.b.WriteByte(' ')
		em.b.WriteString(f.PgType())
		if !f.Nullable {
			em.b.WriteString(" NOT NULL")
		}
		if clause := defaultClause(f); clause != "" {
			em.b.WriteString(clause)
		}
		em.b.WriteString(",\n")
	}
	// Exactly one PK per entity is a Freeze invariant, so at least one
	// constraint line always follows the columns and the last column's
	// trailing comma above is always accounted for.
	em.b.WriteString("    CONSTRAINT ")
	em.b.WriteString(fitName(e.Table + "_pkey"))
	em.b.WriteString(" PRIMARY KEY (")
	em.b.WriteString(quoteIdent(e.PK.Column))
	em.b.WriteString(")")
	for _, f := range e.Fields {
		if f.Unique && !f.PK {
			em.b.WriteString(",\n    CONSTRAINT ")
			em.b.WriteString(fitName(e.Table + "_" + f.Column + "_key"))
			em.b.WriteString(" UNIQUE (")
			em.b.WriteString(quoteIdent(f.Column))
			em.b.WriteString(")")
		}
	}
	for _, f := range e.Fields {
		if f.Type != ir.FieldTypeEnum || len(f.EnumValues) == 0 {
			continue
		}
		em.b.WriteString(",\n    CONSTRAINT ")
		em.b.WriteString(fitName(e.Table + "_" + f.Column + "_check"))
		em.b.WriteString(" CHECK (")
		em.b.WriteString(quoteIdent(f.Column))
		em.b.WriteString(" IN (")
		for i, v := range f.EnumValues {
			if i > 0 {
				em.b.WriteString(", ")
			}
			em.b.WriteString(quoteSQL(v.Value))
		}
		em.b.WriteString("))")
	}
	em.b.WriteString("\n);\n\n")
}

// defaultClause renders a field's `default:` as a SQL DEFAULT clause, per
// spec §3.2: `now` becomes CURRENT_TIMESTAMP; a literal is emitted as a
// single-quoted SQL string (Postgres casts it to the column type); `uuid`
// emits nothing at all, because the generator produces uuids client-side
// with crypto/rand "so create returns the identifier without a round trip"
// -- a database default would contradict the reason the option exists.
func defaultClause(f *ir.Field) string {
	if f.Default == nil {
		return ""
	}
	switch f.Default.Kind {
	case ir.DefaultNow:
		return " DEFAULT CURRENT_TIMESTAMP"
	case ir.DefaultLiteral:
		return " DEFAULT " + quoteSQL(f.Default.Literal)
	default:
		return ""
	}
}

// foreignKeys emits one ALTER TABLE ... ADD FOREIGN KEY per relation.
//
// Foreign keys are ALTERs rather than inline REFERENCES clauses by decision,
// not necessity: two entities that belongTo each other (a nullable mutual
// pair -- user.profile_id and profile.user_id -- is the classic shape)
// resolve cleanly, since only a cycle of *primary keys* is a parse error,
// and no topological order of CREATE TABLEs can satisfy a relation cycle.
// Emitting every FK after every table exists makes the file correct for any
// acyclic or cyclic schema with one uniform shape, at no cost to the
// acyclic case. Self-references are covered by the same uniformity.
func (em *emitter) foreignKeys(e *ir.Entity) {
	for _, rel := range e.Relations {
		if rel.Target == nil || rel.Target.PK == nil {
			// Unreachable through parse.Parse (a Relation is only appended
			// once its target resolved, and Freeze enforces the target's
			// PK); the guard keeps Emit total on any schema it is handed.
			continue
		}
		em.b.WriteString("ALTER TABLE ")
		em.b.WriteString(quoteIdent(e.Table))
		em.b.WriteString(" ADD CONSTRAINT ")
		em.b.WriteString(fitName(e.Table + "_" + rel.Column + "_fkey"))
		em.b.WriteString(" FOREIGN KEY (")
		em.b.WriteString(quoteIdent(rel.Column))
		em.b.WriteString(") REFERENCES ")
		em.b.WriteString(quoteIdent(rel.Target.Table))
		em.b.WriteString(" (")
		em.b.WriteString(quoteIdent(rel.Target.PK.Column))
		em.b.WriteString(") ON DELETE ")
		em.b.WriteString(rel.OnDelete)
		em.b.WriteString(";\n\n")
	}
}

// indexes emits the entity's CREATE INDEX statements: one per declared filter
// prefixed to the sort keys, one for the unfiltered sort, then one per
// declared composite index (spec §3.5, §7.2) -- all plain ascending: a
// btree serves a uniform-direction sort in both directions by backward scan,
// and NULLS FIRST/LAST is never emitted (spec §7.2).
//
// The emitted set is deduplicated by column list, first occurrence wins:
// a filter column that is itself a sort key would otherwise produce a
// derived index identical to the unfiltered one. A single-column list equal
// to the primary key's is skipped entirely -- the pkey constraint already
// created exactly that index.
func (em *emitter) indexes(e *ir.Entity) {
	// The entity's statements collect into their own buffer so an entity
	// whose every index was deduplicated away (an unfiltered sort of just
	// the primary key, say) emits no blank group separator of its own.
	var group strings.Builder
	seen := make(map[string]bool)
	for _, cols := range indexColumnLists(e) {
		key := columnListKey(cols)
		if seen[key] {
			continue
		}
		seen[key] = true
		if len(cols) == 1 && cols[0] == e.PK {
			continue
		}
		names := make([]string, len(cols))
		for i, f := range cols {
			names[i] = f.Column
		}
		group.WriteString("CREATE INDEX ")
		group.WriteString(em.indexName(e.Table, names))
		group.WriteString(" ON ")
		group.WriteString(quoteIdent(e.Table))
		group.WriteString(" (")
		quoted := make([]string, len(names))
		for i, n := range names {
			quoted[i] = quoteIdent(n)
		}
		group.WriteString(strings.Join(quoted, ", "))
		group.WriteString(");\n")
	}
	if group.Len() > 0 {
		// Indexes of one entity group together with no blank line between
		// them; the blank line separates entity groups, mirroring how the
		// tables themselves are separated.
		em.b.WriteString(group.String())
		em.b.WriteByte('\n')
	}
}

// indexColumnLists returns the entity's index column lists in emission
// order: one per declared filter (declaration order), the unfiltered sort,
// then each declared composite index (declaration order) -- each with the
// sort keys appended after the equality columns, per spec §7.2's rule that
// an equality-constrained column yields a constant equivalence class and
// generates no pathkey. A sort key already among the equality columns is
// dropped from the suffix for the same reason: it is constant under every
// seek the index serves.
func indexColumnLists(e *ir.Entity) [][]*ir.Field {
	sortCols := make([]*ir.Field, len(e.Sort.Keys))
	for i, k := range e.Sort.Keys {
		sortCols[i] = k.Field
	}

	var lists [][]*ir.Field
	for i := range e.Filters {
		lists = append(lists, prefixWithSortKeys([]*ir.Field{e.Filters[i].Field}, sortCols))
	}
	lists = append(lists, sortCols)
	for _, idx := range e.Indexes {
		prefix := make([]*ir.Field, len(idx.Columns))
		for i, c := range idx.Columns {
			prefix[i] = c.Field
		}
		lists = append(lists, prefixWithSortKeys(prefix, sortCols))
	}
	return lists
}

// prefixWithSortKeys appends every sort key not already present among
// prefix's columns, in order, to prefix.
func prefixWithSortKeys(prefix, sortCols []*ir.Field) []*ir.Field {
	present := make(map[*ir.Field]bool, len(prefix))
	for _, f := range prefix {
		present[f] = true
	}
	out := make([]*ir.Field, 0, len(prefix)+len(sortCols))
	out = append(out, prefix...)
	for _, f := range sortCols {
		if !present[f] {
			out = append(out, f)
		}
	}
	return out
}

// columnListKey renders cols as a dedup key. Column names are unique within
// an entity (a parse invariant), so the name sequence identifies the field
// sequence exactly; the NUL separator keeps "a","b" distinct from "a\x00b".
func columnListKey(cols []*ir.Field) string {
	var b strings.Builder
	for i, f := range cols {
		if i > 0 {
			b.WriteByte(0)
		}
		b.WriteString(f.Column)
	}
	return b.String()
}

// indexName derives the CREATE INDEX name for table and cols:
// <table>_<col1>_..._<colN>_idx, kept unique within what Postgres can hold.
// Two hazards the plain form cannot survive: a name longer than the 63-byte
// identifier limit (Postgres truncates silently, so two prefix-sharing names
// collide) and two distinct column lists joining to the same text (columns
// "a_b" and "a","b" -- real within one table, since column names may contain
// underscores). Both are resolved the same way: fitName truncates, and a
// collision with a name already emitted is broken by a deterministic salted
// hash of the full name and column list.
func (em *emitter) indexName(table string, cols []string) string {
	name := table + "_" + strings.Join(cols, "_") + "_idx"
	candidate := fitName(name)
	for salt := 0; em.names[candidate]; salt++ {
		h := fnv.New64a()
		fmt.Fprintf(h, "%d\x00%s\x00%s", salt, name, strings.Join(cols, "\x00"))
		candidate = fitName(fmt.Sprintf("%s_%012x", name, h.Sum64()))
	}
	em.names[candidate] = true
	return candidate
}

// fitName returns name unchanged when it fits within Postgres's identifier
// limit, and otherwise truncates it and appends 12 hex digits of an FNV-1a
// hash of the full name -- deterministic, and distinct for distinct full
// names, where Postgres's own silent truncation would leave two prefix-
// sharing names indistinguishable. Derived names only (constraints, indexes):
// table and column names themselves are rejected, never mangled, when too
// long (internal/parse's identifier rule).
func fitName(name string) string {
	if len(name) <= maxIdentifierBytes {
		return name
	}
	h := fnv.New64a()
	h.Write([]byte(name))
	suffix := fmt.Sprintf("_%012x", h.Sum64())
	return name[:maxIdentifierBytes-len(suffix)] + suffix
}

// quoteSQL renders s as a single-quoted SQL string literal, doubling embedded
// single quotes. Backslashes need no handling: Postgres's
// standard_conforming_strings is on by default and this project emits no
// escape-string literals. Every value reaching here (enum members, `default:`
// literals) has already passed the parser's no-control-characters rule, so
// the literal is single-line and NUL-free; doubling quotes is then the
// complete escaping story.
func quoteSQL(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// quoteIdent renders s as a double-quoted SQL identifier. Every table and
// column name is emitted through here, whatever its spelling: the parser's
// identifier grammar accepts Postgres reserved words ("order", "select",
// "user" are all valid schema field names -- the canonical example's `user`
// entity only escapes collision through pluralisation), and an unquoted
// reserved word in a table or column position is a syntax error at apply
// time. Quoting everything -- the pg_dump convention -- makes that class of
// bug unrepresentable rather than maintained against a keyword list that
// drifts with Postgres versions. Input is already validated against the
// identifier grammar (no quotes, no NULs), so the doubling below is totality,
// not an expected path. Derived names (constraints, indexes) are built from
// identifier segments plus fixed suffixes and are never reserved words, so
// they pass unquoted.
func quoteIdent(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
}
